import type { Metadata } from "next";
import localFont from "next/font/local";
import ApolloSetting from "../commons/apollo-setting";
import "./globals.css";
import Layout from "@/commons/layout";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const 글로벌폰트 = localFont({
  src: "./fonts/Pretendard-Regular.woff2",
  variable: "--글로벌폰트",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${글로벌폰트.variable}`}>
        <ApolloSetting>
          <Layout>{children}</Layout>
        </ApolloSetting>
      </body>
    </html>
  );
}
